# Generated by Django 5.1.1 on 2025-04-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_enabled', models.BooleanField(default=True)),
                ('blacklist_enabled', models.BooleanField(default=True)),
                ('logs_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
