# Generated by Django 5.2 on 2025-04-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_proxysettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxysettings',
            old_name='blacklist_enabled',
            new_name='blacklist_active',
        ),
        migrations.RenameField(
            model_name='proxysettings',
            old_name='logs_enabled',
            new_name='logging_active',
        ),
        migrations.RenameField(
            model_name='proxysettings',
            old_name='proxy_enabled',
            new_name='proxy_active',
        ),
    ]
